#!/bin/bash

printf "\ntests for ~:\n"
echo ~-
printf "~- is correct\n"
cd ..
echo ~-
printf "/Users/login/.../minishell\n"
echo max""
printf "max\n"
echo max''
printf "max\n"
echo max' '
printf "max\n"




error double quote shall now quit

can i eare the first char in cl after i write?

$> echo "1""1"
arg count 2
1
whyyyyy????


malloc protect all allocs

$> echo "dsad"~"dsad"
dsad/Users/mrantildsad
bash-3.2$ echo "sadsad"~"dsada"
sadsad~dsada

check why valgrind errors occur with error commands