#!/bin/bash

printf "\ntests for ~:\n"
echo ~-
printf "~- is correct\n"
cd ..
echo ~-
printf "/Users/login/.../minishell\n"
echo max""
printf "max\n"
echo max''
printf "max\n"
echo max' '
printf "max\n"

ls       -"l"a